"""Init models 2

Revision ID: b0a4adacc259
Revises: d2ee55e3f792
Create Date: 2024-12-15 15:06:26.657886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a4adacc259'
down_revision = 'd2ee55e3f792'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
